import { defineConfig } from 'vite'
import preact from '@preact/preset-vite'
import { resolve } from 'path'
import { readdirSync } from 'fs'

/** Inject Plausible Analytics script into all HTML pages at build time */
function plausiblePlugin() {
  return {
    name: 'inject-plausible',
    transformIndexHtml(html) {
      const script = '<script defer data-domain="mergecombinator.com" src="https://plausible.io/js/script.js"></script>'
      return html.replace('</head>', `  ${script}\n</head>`)
    },
  }
}

export default defineConfig({
  plugins: [preact(), plausiblePlugin()],
  resolve: {
    alias: {
      'react': 'preact/compat',
      'react-dom': 'preact/compat',
    },
  },
  server: {
    host: '0.0.0.0',
    port: 3000,
    open: true,
    allowedHosts: ['macbook-pro.tail45afa7.ts.net'],
    proxy: {
      '/api': {
        target: 'https://webhook-667608980042.us-central1.run.app',
        changeOrigin: true,
        rewrite: (path) => path.replace(/^\/api/, ''),
        secure: true
      }
    }
  },
  build: {
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
        signals: resolve(__dirname, 'signals.html'),
        portfolio: resolve(__dirname, 'portfolio.html'),
        builders: resolve(__dirname, 'builders.html'),
        'founder-path': resolve(__dirname, 'founder-path.html'),
        dashboard: resolve(__dirname, 'dashboard.html'),
        status: resolve(__dirname, 'status.html'),
        merch: resolve(__dirname, 'merch.html'),
        opportunities: resolve(__dirname, 'opportunities.html'),
        knowledge: resolve(__dirname, 'knowledge.html'),
        privacy: resolve(__dirname, 'privacy.html'),
        terms: resolve(__dirname, 'terms.html'),
        security: resolve(__dirname, 'security.html'),
        archive: resolve(__dirname, 'archive.html'),
        access: resolve(__dirname, 'access.html'),
        'access-quick': resolve(__dirname, 'access-quick.html'),
        contribute: resolve(__dirname, 'contribute.html'),
        // combine.html removed - redirects to /programs/the-combine
        wingman: resolve(__dirname, 'wingman.html'),
        learn: resolve(__dirname, 'learn.html'),
        'learn-read': resolve(__dirname, 'learn/read.html'),
        guild: resolve(__dirname, 'guild.html'),
        briefs: resolve(__dirname, 'briefs.html'),
        about: resolve(__dirname, 'about.html'),
        'ai-overview': resolve(__dirname, 'ai/overview.html'),
        '404': resolve(__dirname, '404.html'),
        // Combine cohorts
        'combine-cohort25-1': resolve(__dirname, 'combine/cohort25-1.html'),
        // Programs
        'programs-index': resolve(__dirname, 'programs/index.html'),
        'programs-combine': resolve(__dirname, 'programs/the-combine.html'),
        'programs-residency': resolve(__dirname, 'programs/residency.html'),
        // Knowledge base
        'knowledge-gtm': resolve(__dirname, 'knowledge/go-to-market.html'),
        'knowledge-acq': resolve(__dirname, 'knowledge/acquisition.html'),
        'knowledge-sbir': resolve(__dirname, 'knowledge/sbir.html'),
        'knowledge-compliance': resolve(__dirname, 'knowledge/compliance.html'),
        'knowledge-defense-venture-studio': resolve(__dirname, 'knowledge/defense-venture-studio.html'),
        // Signals articles
        'signals-counter-drone': resolve(__dirname, 'signals/counter-drone-jiatf-401.html'),
        'signals-ndaa': resolve(__dirname, 'signals/ndaa-speed-act.html'),
        'signals-eisenhower': resolve(__dirname, 'signals/uss-eisenhower-lessons.html'),
        'signals-ulysses': resolve(__dirname, 'signals/ulysses-combine-to-series-a.html'),
        'signals-residency': resolve(__dirname, 'signals/missionized-tech-residency.html'),
        'signals-interceptors': resolve(__dirname, 'signals/interceptor-stockpile-crisis.html'),
        'signals-dawg': resolve(__dirname, 'signals/dawg-54-billion-problem.html'),
        'signals-vc-alignment': resolve(__dirname, 'signals/vc-defense-alignment-problem.html'),
        'signals-african-lion': resolve(__dirname, 'signals/mchmr-african-lion-26.html'),
        'signals-army-acquisition': resolve(__dirname, 'signals/army-rewriting-acquisition.html'),
        // FAQ page (generated by optimize-static.mjs)
        'faq': resolve(__dirname, 'faq.html'),
        // Entity pages (generated by optimize-static.mjs)
        ...Object.fromEntries(
          (() => {
            try {
              return readdirSync(resolve(__dirname, 'companies'))
                .filter(f => f.endsWith('.html'))
                .map(f => [`companies-${f.replace('.html', '')}`, resolve(__dirname, 'companies', f)]);
            } catch { return []; }
          })()
        ),
      }
    },
    // Copy public folder to output (includes _redirects, _headers for Cloudflare)
    copyPublicDir: true
  }
})
